config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  get 'profile', to: 'pages#profile'
  get 'profile/edit', to: 'pages#edit'
  patch 'profile/update', to: 'pages#update'
  get 'dashboard', to: 'pages#dashboard'
  get 'profile/subjects', to: 'pages#subjects', as: 'profilesubjects'
  get 'search', to: 'pages#search'
  get '/groups/:id/join', to: 'groups#join', as: 'join_group'
  get 'attendances', to: 'sessions#index'
  delete 'attendances/:id', to: 'attendances#destroy', as: 'attendancedestroy'

  #get 'show', to: 'sessions#show'
  #post 'create', to: 'sessions#create'
  #get 'new', to: 'sessions#new'


  resources :sessions, only: %i[show create new destroy edit] do
    resources :attendances, only: %i[create]
    resources :comments, only: %i[create]
  end

  resources :memberships, only: %i[destroy]
  resources :attendances, only: %i[update]

  resources :interested_subjects, only: %i[new create]
  #resources :sessions, only: %i[new create]

  resources :groups do
    member do
      post 'join'
    end

    resources :sessions, except: %i[index show new create edit] do
      member do
        post 'join'
      end
    end
  end

  devise_for :users
end

app/models/group.rb
class Group < ApplicationRecord
  # mount_uploader :group_picture, GroupPictureUploader
  belongs_to :user
  belongs_to :subject
  has_many :memberships, dependent: :destroy
  has_many :sessions, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @page_title = "My Groups"
    @user = current_user
    @group_ids = @user.memberships.pluck(:group_id)
    @my_groups = Group.where(id: @group_ids)
    @created_groups = Group.where(user_id: current_user.id)
  end

  def show
    @page_title = "Group Info"
    @group = Group.find(params[:id])
  end

  def new
    @page_title = "Create Group"
    @group = Group.new
    @subjects = Subject.all
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save!
      @subject = Subject.find(@group.subject_id)
      InterestedSubject.create(subject: @subject, user: current_user) unless current_user.subjects.include? @subject
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end


  def update
    @group = current_user.groups.find(params[:id])

    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  def join
    @group = Group.find(params[:id])
    @membership = Membership.new(group: @group, user: current_user)
    @membership.save
    @session = Session.find_by(group: @group)

    redirect_to @group, notice: 'Yay! 🎉 You have joined the group.'
  end
  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path, notice: 'Yay! 🎉You succesfully deleted this group'
  end

  private

  def group_params
    params.require(:group).permit(:name, :description, :group_picture, :subject_id)
  end
end

app/views/groups/edit.html.erb
<%= render "shared/navbar" %>
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Edit Group</h3>
          <%= simple_form_for @group do |f| %>
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :group_picture, as: :file %>
            <%= f.association :subject, collection: @subjects, label: 'Select Subject' %>
            <%= f.submit class: "btn btn-primary m-3", style: "background-color: #4e6cf0ef;" %>

          <% end %>

      </div>
    </div>
  </div>
</div>
<%= render "shared/navbar_bottom" %>

app/views/groups/index.html.erb
<%= render "shared/navbar" %>
<div class="container text-center">
  <div class="cards">
    <h2><strong>Created Groups</strong></h2>
    <% @created_groups.each do |group| %>
      <div class="group-card">
        <%= link_to group_path(group) do %>
          <div class="group-image">
            <img src="https://res.cloudinary.com/dbe6henkk/image/upload/v1693559281/<%= group.group_picture %>" />
          </div>
          <div class="group-details">
            <div class="group-name mt-2">
              <%= group.name %>
            </div>
          </div>
        <% end %>
        <% if group.user == current_user %>
          <div class="edit-delete-icons">
            <%= link_to edit_session_path(session) do %>
                <i class="fa-solid fa-pen-to-square" style="color: #0e2954; font-size: 20px; margin: 5px;"></i>
            <% end %>
            <%= link_to session_path(session), data: { turbo_confirm: 'Are you sure?', turbo_method: :delete } do %>
                <i class="fa-solid fa-trash-can" style="color: #0e2954; font-size: 20px;"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
    <%= link_to "Create Group", new_group_path , class: " btn btn-primary m-3 w-3" %>
    <div class="card bg-dark my-5"></div>
    <h2><strong>Groups I'm a member of</strong></h2>
      <% @my_groups.each do |group| %>
        <div class="group-card">
          <%= link_to group_path(group) do %>
          <div class="group-image">
              <img src="https://res.cloudinary.com/dbe6henkk/image/upload/v1693559281/<%= group.group_picture %>" />
          </div>
          <div class="group-details">
            <div class="group-name"><%= group.name %></div>
            <% actual_member =  Membership.find_by(group: group) %>
            <%= link_to 'Leave', membership_path(actual_member), data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }, class: "btn btn-danger m-3 text-light",  style: "border-radius: 20px;" %>
          </div>
          <% end %>
      </div>
    <% end %>
  </div>
</div>
<%= render "shared/navbar_bottom" %>

<%# <script>
  document.querySelectorAll('.delete-group i').forEach(function(icon) {
    icon.addEventListener('click', function() {
      var groupId = this.getAttribute('data-group-id');
      var confirmDelete = confirm('Are you sure you want to delete this group?');

      if (confirmDelete) {

        alert('Group with ID ' + groupId + ' deleted.');
      }
    });
  });
</script> %>

app/views/groups/new.html.erb
<%= render "shared/navbar" %>
<div class="container">
  <div class="bg-white rounded p-3 shadow text-dark">
      <%= simple_form_for @group do |f| %>
        <%= f.input :name %>
        <%= f.input :description%>
        <%= f.input :group_picture, as: :file %>
        <%= f.association :subject, collection: @subjects, label: 'Select Subject' %>
        <%= f.submit class: "btn btn-primary m-3" %>
      <% end %>
  </div>
</div>
<%= render "shared/navbar_bottom" %>

app/views/groups/show.html.erb
<%= render "shared/navbar" %>
<div class="container text-center">
  <div class="cards">
    <div class="group-card">
      <div class="group-image">
        <h2><%= @group.name %></h2>
        <img src="https://res.cloudinary.com/dbe6henkk/image/upload/v1693559281/<%= @group.group_picture %>" alt="<%= @group.name %> Image"  />
      </div>
      <div class="group-details">
        <%= @group.description %>
      </div>
    </div>
  </div>
  <h2 class="text-center mt-3"><strong>Upcoming Sessions</strong></h2>
  <div id="session-cards">
    <% @group.sessions.each do |session| %>
      <div class="session-card" >
        <div class="session-name text-white p-3">
          <p><i class="fas fa-map-marker-alt"></i>  <%= session.city %> </p>
          <p><i class="fas fa-info-circle"></i> <%= session.description %> </p>
          <p><i class="far fa-calendar"></i> <%= session.time.strftime('%d-%m-%Y') %></p>
          <p><i class="fa-solid fa-clock"></i><%= session.time.strftime('%H:%M:%S') %></p>
        </div>
      </div>
    <% end %>
  </div>

  <% if Membership.where(user: current_user, group: @group).empty? %>
  <%= link_to 'Join Group', join_group_path(@group), data:{turbo_method: :post}, class: 'btn btn-primary' %>
  <% else %>
  <div class="card-going"> <h6>"You are member of this group"</h6> </div>
  <% end %>

<%= render "shared/navbar_bottom" %>