config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  get 'profile', to: 'pages#profile'
  get 'profile/edit', to: 'pages#edit'
  patch 'profile/update', to: 'pages#update'
  get 'dashboard', to: 'pages#dashboard'
  get 'profile/subjects', to: 'pages#subjects', as: 'profilesubjects'
  get 'search', to: 'pages#search'
  get '/groups/:id/join', to: 'groups#join', as: 'join_group'
  get 'attendances', to: 'sessions#index'
  delete 'attendances/:id', to: 'attendances#destroy', as: 'attendancedestroy'

  #get 'show', to: 'sessions#show'
  #post 'create', to: 'sessions#create'
  #get 'new', to: 'sessions#new'


  resources :sessions, only: %i[show create new destroy edit] do
    resources :attendances, only: %i[create]
    resources :comments, only: %i[create]
  end

  resources :memberships, only: %i[destroy]
  resources :attendances, only: %i[update]

  resources :interested_subjects, only: %i[new create]
  #resources :sessions, only: %i[new create]

  resources :groups do
    member do
      post 'join'
    end

    resources :sessions, except: %i[index show new create edit] do
      member do
        post 'join'
      end
    end
  end

  devise_for :users
end

app/views/shared/_flashes.html.erb
<% if notice %>
<div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <%= notice %>
  <a data-bs-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>
  
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="d-flex justify-content-between container-fluid">
    <div class="logo">
      <%= link_to dashboard_path do %>
        <%= image_tag "https://res.cloudinary.com/ddfjqexgw/image/upload/v1694003099/lookat_mq35gt.png" %>
      <% end %>
    </div>
    <h1 class="page-title"><strong><%= @page_title %></strong></h1>
        <% if current_user %>
          <div class="d-flex nav-item dropdown">
            <div class="notification-icon mx-2">
              <img src="https://res.cloudinary.com/ddfjqexgw/image/upload/v1694093446/noticiationicon_xmpx9k.png"/>
              <div class="pending-count <%= 'show' if @pending_requests_count > 0 %>">
                <%= link_to profile_path, class:"text-white" do %>
                  <%= @pending_requests_count %>
                <% end %>
              </div>
            </div>
          <% if current_user.picture? %>
            <a href="#" class="user-profile" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <img src="https://res.cloudinary.com/dbe6henkk/image/upload/v1693559281/<%= current_user.picture %>" />
            </a>
          <% else %>
            <%= image_tag "https://res.cloudinary.com/ddfjqexgw/image/upload/v1693490930/DefaultAvatar_zwdogj.jpg" %>
          <% end %>
        <% else %>
          <div>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </div>
        <% end %>
      <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <%= link_to "Profile", profile_path, class: "dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar_bottom.html.erb
<div class="bottom-navbar">
  <%= link_to dashboard_path do %>
    <i class="fas fa-house-chimney <%= 'active' if current_page?(dashboard_path) %>"></i>
  <% end %>
  <%= link_to search_path do %>
    <i class="fas fa-search <%= 'active' if current_page?(search_path) %>"></i>
  <% end %>
  <%= link_to groups_path do %>
    <i class="fa-solid fa-people-group <%= 'active' if current_page?(groups_path) %>"></i>
  <% end %>
  <%= link_to attendances_path do %>
    <i class="fa-regular fa-calendar-days <%= 'active' if current_page?(attendances_path) %>"></i>
  <% end %>
</div>