config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  get 'profile', to: 'pages#profile'
  get 'profile/edit', to: 'pages#edit'
  patch 'profile/update', to: 'pages#update'
  get 'dashboard', to: 'pages#dashboard'
  get 'profile/subjects', to: 'pages#subjects', as: 'profilesubjects'
  get 'search', to: 'pages#search'
  get '/groups/:id/join', to: 'groups#join', as: 'join_group'
  get 'attendances', to: 'sessions#index'
  delete 'attendances/:id', to: 'attendances#destroy', as: 'attendancedestroy'

  #get 'show', to: 'sessions#show'
  #post 'create', to: 'sessions#create'
  #get 'new', to: 'sessions#new'


  resources :sessions, only: %i[show create new destroy edit] do
    resources :attendances, only: %i[create]
    resources :comments, only: %i[create]
  end

  resources :memberships, only: %i[destroy]
  resources :attendances, only: %i[update]

  resources :interested_subjects, only: %i[new create]
  #resources :sessions, only: %i[new create]

  resources :groups do
    member do
      post 'join'
    end

    resources :sessions, except: %i[index show new create edit] do
      member do
        post 'join'
      end
    end
  end

  devise_for :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, :address, :age, presence: true
  has_many :created_groups, class_name: "Group", dependent: :destroy
  has_many :interested_subjects
  has_many :memberships, dependent: :destroy
  has_many :attendances, dependent: :destroy
  has_many :sessions, through: :attendances
  has_many :subjects, through: :interested_subjects
  has_many :groups, through: :memberships
end

app/views/pages/_info_window.html.erb
<div class="text-center p-1">
  <h4><%= session.name %></h4>
</div>

app/views/pages/_marker.html.erb
<%= image_tag "https://res.cloudinary.com/ddfjqexgw/image/upload/v1693948624/sessionicon_ed36ln.png", class: "marker-map", width: 10, alt: "Logo" %>

app/views/pages/dashboard.html.erb
<%= render "shared/navbar" %>
<div class="container">
  <div class="map d-flex justify-content-center mt-3">
    <div style="width: 90%; height: 258px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
  <h2 class="text-center mt-3 upcoming"><strong>Upcoming Sessions</strong></h2>
  <% if @my_sessions.empty? %>
    <p class="text-center text-light mt-3">You don't have any sessions :(</p>
    <div class="button-container text-center">
      <%= link_to "Edit your subjects", profilesubjects_path, class: "btn m-3 edit-button ", style: "border-radius: 20px;" %>
    </div>
  <% end %>
  <% @my_sessions.each do |session| %>
    <div class="session-card">
      <div class="session-details">
        <%= link_to session_path(session) do %>
        <div class="d-flex justify-content-between ">
          <div>
            <div class="session-name"><%= session.name %></div>
            <p><i class="far fa-calendar"></i> <%= session.time.strftime('%-d %B %Y') %></p>
            <p><i class="fa-solid fa-clock"></i> <%= session.time.strftime('%H:%M') %></p>
          </div>
          <div>
            <%= image_tag "https://res.cloudinary.com/ddfjqexgw/image/upload/v1693663058/icons/#{session.group.subject.icon_creator}", class:"icon-creator" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<%= render "shared/navbar_bottom" %>

app/views/pages/home.html.erb
<div class="background-home">
  <div class="container-home text-center mt-1">
    <div class="container mt-1">
      <div class="title-home">
        <h1>StudyBuddy</h1>
      </div>
      <p class="mb-4 text-home">Group. Learn. Thrive.</p>
      <div class="homepage-img">
        <%= image_tag "back.png", style: "width: 350px; margin: 0 auto; max-height: 380px" %>
      </div>
      <div class="header-home mx-2">
        <div class="subtitle-home">
          <h5 class="mt-2">Welcome to StudyBuddy</h5>
        </div>
        <div class="description-home">
          <h6>Empower your studies with collaborative learning on StudyBuddy's dynamic platform.</h6>
        </div>
      </div>
      <div class="mt-5">
        <%= link_to "Register", new_user_registration_path, class: "btn btn-primary" %>
      </div>
      <div class="mt-3">
        <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
      </div>
      <div class="mt-3">
        <%= link_to "Continue as a Guest", dashboard_path, class: "guest-button" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<%= render "shared/navbar" %>
<div class="container text-center">
  <div class="d-flex text-center mt-4">
    <div class="user-profile profile-page mx-3">
      <img src="https://res.cloudinary.com/dbe6henkk/image/upload/v1693559281/<%= current_user.picture %>" />
    </div>
    <div>
      <h3 class="m-3"><%= @user.first_name %> <%= @user.last_name %></h3>
      <h3>🌎 <%= @user.address %></h3>
    </div>
  </div>
  <h2 class="m-4 mt-5"><strong>Requests to my sessions</strong></h2>
  <% if @requests.empty? %>
    <p style="color: #F0EEED">You don't have any requests</p>
  <% end %>
  <% @requests.each do |request| %>
    <div class="request mx-3">
      <div class='request-left'>
        <div class="user-profile">
          <img src="https://res.cloudinary.com/dbe6henkk/image/upload/v1693559281/<%= request.user.picture %>" />
        </div>
        <div class="request-info">
          <div class="request-info-title">
            <%= request.user.first_name %>
          </div>
          <div class="request-info-details">
            <p><i class="far fa-calendar"></i> <%= request.session.time.strftime('%-d %B %Y') %></p>
            <p><i class="fa-solid fa-clock"></i> <%= request.session.time.strftime('%H:%M') %></p>
          </div>
        </div>
      </div>
      <p><%= request.session.name %></p>
      <div class="request-actions">
        <% if request.pending? %>
          <%= simple_form_for request do |f| %>
            <%= f.input :status, as: :hidden, input_html: { value: 'Accepted'} %>
            <%= f.submit '✅', class: 'btn btn-accepted' %>
          <% end %>
          <%= simple_form_for request do |f| %>
            <%= f.input :status, as: :hidden, input_html: { value: 'Rejected'} %>
            <%= f.submit '❌', class: 'btn btn-light' %>
          <% end %>
        <% elsif request.status === "Accepted" %>
          <p class="request-tag-accepted"><%= request.status %></p>
        <% elsif request.status === "Rejected" %>
          <p class="request-tag-rejected"><%= request.status %></p>
        <% end %>
      </div>
    </div>
  <% end %>
  <h2 class="m-4 mt-5"><strong>Submitted requests</strong></h2>
  <% if @my_requests.empty? %>
    <p style="color: #f0eeedc3">You don't have any submitted requests</p>
  <% end %>
  <% @my_requests.each do |request| %>
    <% if request.status == "Accepted" %>
      <div class="card card-accepted mx-3 mb-2">
        <p><%= request.session.name %></p>
        <p><strong><%= request.status %></strong></p>
      </div>
    <% elsif request.status == "Rejected" %>
      <div class="card card-rejected mx-3 mb-2">
        <p><%= request.session.name %></p>
        <p><strong><%= request.status %></strong></p>
      </div>
    <% else %>
      <div class="card card-pending mx-3 mb-2">
        <p><%= request.session.name %></p>
        <p><strong><%= request.status %> ⏰</strong></p>
      </div>
    <% end %>
  <% end %>
  <h2 class="m-4 mt-5"><strong>My Subjects</strong></h2>
  <% @subjects.each do |subject| %>
    <div class="card bg-dark mt-3"></div>
    <div class="d-flex justify-content-between align-items-center p-2 subjects-card text-center text-white">
      <%= image_tag "https://res.cloudinary.com/ddfjqexgw/image/upload/v1693663058/icons/#{subject.icon_creator}", class:"icon-creator" %>
      <p class="name-subject-profile"><strong><%= subject.name %></strong></p>
      <div class="btn btn-red"><p><strong>X</strong></p></div>
    </div>
    <div class="card bg-dark"></div>
  <% end %>
  <div class="button-container">
    <%= link_to "Edit your subjects", profilesubjects_path, class: "btn m-3 edit-button ", style: "border-radius: 20px;" %>
  </div>
</div>
<%= render "shared/navbar_bottom" %>

app/views/pages/search.html.erb
<%= render "shared/navbar" %>
<div class="container">
  <%= form_tag search_path, method: :get do %>
    <div class="search-container mb-2">
      <%= text_field_tag :search, params[:search], placeholder: 'Search', class: "input-width search-input text-light" %>
      <button type="submit" class="search-button">
        <i class="fas fa-search"></i>
      </button>
    </div>
  <% end %>
  <h1 class="text-center">Groups</h1>
  <div class="cards">
    <% @groups.each do |group| %>
      <a href="<%= group_path(group) %>">
        <div class="d-flex align-items-center p-2 group-card-search">
          <%= image_tag "https://res.cloudinary.com/ddfjqexgw/image/upload/v1693663058/icons/#{group.subject.icon_creator}", class:"icon-creator" %>
          <div class="group-details">
            <div class="group-name text-center"><%= group.name %></div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
  <div class="card bg-dark my-4"></div>
  <h1 class="text-center">Sessions</h1>
  <% @sessions.each do |session| %>
    <div class="session-card">
      <div class="session-details">
        <%= link_to session_path(session) do %>
          <div class="d-flex justify-content-between">
            <div>
              <div class="session-name"><%= session.name %></div>
              <p><i class="far fa-calendar"></i> <%= session.time.strftime('%-d %B %Y') %></p>
              <p><i class="fa-solid fa-clock"></i><%= session.time.strftime('%H:%M') %></p>
            </div>
            <div>
              <%= image_tag "https://res.cloudinary.com/ddfjqexgw/image/upload/v1693663058/icons/#{session.group.subject.icon_creator}", class:"icon-creator" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<%= render "shared/navbar_bottom" %>

app/views/pages/subjects.html.erb
<div class="container m-0 text-center">
  <div class="mt-5">
    <h2>Choose your subjects of interest</h2>
  </div>
  <div class="container mt-4">
    <%= simple_form_for(@interested_subject) do |f| %>
      <%= f.association :subject, collection: @subjects,  as: :check_boxes, include_hidden: false, input_html: { class: "tag-selector", multiple: true, checked: current_user.subject_ids }, item_wrapper_class: 'tag-item text-center' %>
      <div class="text-center">
        <%= f.submit "Add these subjects", class: "btn edit-button " %>
      </div>
    <% end %>
    <div class="text-center">
      <%= link_to "Skip this part", dashboard_path, class: "btn edit-button mt-3 " %>
    </div>
  </div>
</div>